# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- 18-ISbo-2a

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    architecture: 'x64'

- script: | 
    pip install coverage
    pip install httplib2
    pip install requests
    pip install --upgrade google-api-python-client
    pip install --upgrade oauth2client
    pip install google-auth-oauthlib
  displayName: 'Install libraries'

- script: | 
    cd "email//18-ISbo-2a"
    coverage run -m unittest discover
    coverage xml APIgoogle.py client.py Validation.py
  displayName: 'Run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'coverage.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)' 
    artifactName: 'drop' 
    publishLocation: 'Container'
